// Generated by `asql` — do not edit. Regenerate with:
//   asql render --preset workers-logs --out src/analytics-catalog.ts

export const catalog = {
  "notes": [
    "Double-quote camelCase identifiers to be safe: \"httpStatus\", \"scriptName\".",
    "Time buckets: toStartOfInterval(timestamp, INTERVAL 5 MINUTE).",
    "Adaptively sampled datasets have a sampleInterval column: estimate counts with sum(\"sampleInterval\"), conditional counts with sumIf(\"sampleInterval\", cond), percentiles with quantileWeighted(0.99, col, \"sampleInterval\"). count() gives sampled rows only. Call sum(\"sampleInterval\") results estimated events, not sampled events; when an estimate is small, add count() to show how many rows it rests on.",
    "Data is already scoped to your account; don't filter on accountTag."
  ],
  "tables": [
    {
      "name": "logs.workersLogs",
      "title": "Workers Logs",
      "description": "Invocation and custom logs emitted by Cloudflare Workers",
      "timeColumn": "timestamp",
      "columns": [
        {
          "name": "cpuTimeMs",
          "type": "UInt32",
          "description": "Worker CPU execution time in milliseconds"
        },
        {
          "name": "error",
          "type": "String",
          "description": "Error associated with the log"
        },
        {
          "name": "httpStatus",
          "type": "Int64",
          "description": "HTTP status code returned by the Worker"
        },
        {
          "name": "id",
          "type": "String",
          "description": "Unique sortable log identifier"
        },
        {
          "name": "invocationLabel",
          "type": "String",
          "description": "Raw invocation display label; use the type-specific columns when available"
        },
        {
          "name": "invocationType",
          "type": "String",
          "description": "Workers handler type, such as fetch, scheduled, queue, or rpc"
        },
        {
          "name": "level",
          "type": "String",
          "description": "Log severity level"
        },
        {
          "name": "logType",
          "type": "String",
          "description": "Whether the row is a custom or invocation log"
        },
        {
          "name": "message",
          "type": "String",
          "description": "Human-readable log message"
        },
        {
          "name": "rayId",
          "type": "String",
          "description": "Cloudflare Ray ID associated with the invocation"
        },
        {
          "name": "requestId",
          "type": "String",
          "description": "Identifier linking logs from one Worker invocation"
        },
        {
          "name": "sampleInterval",
          "type": "Int64",
          "description": "Effective sampling interval used to weight the log"
        },
        {
          "name": "scriptName",
          "type": "String",
          "description": "Worker script that emitted the log"
        },
        {
          "name": "spanId",
          "type": "String",
          "description": "Associated span identifier"
        },
        {
          "name": "timestamp",
          "type": "DateTime64(3)",
          "description": "Time at which the log was emitted"
        },
        {
          "name": "traceId",
          "type": "String",
          "description": "Associated distributed trace identifier"
        },
        {
          "name": "transactionName",
          "type": "String",
          "description": "Normalized transaction name for the invocation"
        },
        {
          "name": "url",
          "type": "String",
          "description": "Request URL associated with the invocation"
        },
        {
          "name": "wallTimeMs",
          "type": "UInt32",
          "description": "Worker wall-clock execution time in milliseconds"
        }
      ],
      "sampling": "adaptive",
      "examples": [
        {
          "question": "Invocations and 5xx per script",
          "sql": "SELECT \"scriptName\", sum(\"sampleInterval\") AS invocations, sumIf(\"sampleInterval\", \"httpStatus\" >= 500) AS errors\nFROM logs.workersLogs\nWHERE timestamp >= now() - INTERVAL '1 day' AND \"logType\" = 'cf-worker-event'\nGROUP BY \"scriptName\" ORDER BY invocations DESC LIMIT 20"
        },
        {
          "question": "p99 wall time per script",
          "sql": "SELECT \"scriptName\", quantileWeighted(0.99, \"wallTimeMs\", \"sampleInterval\") AS p99_wall_ms\nFROM logs.workersLogs\nWHERE timestamp >= now() - INTERVAL '1 day' AND \"logType\" = 'cf-worker-event'\nGROUP BY \"scriptName\" ORDER BY p99_wall_ms DESC LIMIT 20"
        },
        {
          "question": "Most common error messages",
          "sql": "SELECT \"scriptName\", message, sum(\"sampleInterval\") AS n\nFROM logs.workersLogs\nWHERE timestamp >= now() - INTERVAL '1 day' AND level = 'error'\nGROUP BY \"scriptName\", message ORDER BY n DESC LIMIT 20"
        }
      ],
      "notes": [
        "logType 'cf-worker-event' = one row per invocation (has httpStatus, wallTimeMs, cpuTimeMs). logType 'cf-worker' = console.log lines (httpStatus is 0).",
        "invocationType values seen: fetch, scheduled, alarm, jsrpc (also queue, email, … if used).",
        "level: console lines are '' (console.log), 'debug', 'warn' or 'error'; invocation rows are 'info', or 'error' when the invocation failed."
      ]
    }
  ]
} as const;
