/**
 * AI SDK 7 adapter.
 *
 *   import { analyticsSQLTools } from "cf-agent-sql/ai-sdk";
 *   import { catalog } from "./analytics-catalog"; // generated by `asql render --out`
 *   new ToolLoopAgent({ model, tools: analyticsSQLTools({ binding: env.ANALYTICS, catalog }) });
 */
import { tool, type ToolSet } from "ai";
import { z } from "zod";
import { CATALOG_SEARCH_DESCRIPTION } from "./catalog";
import {
  type AnalyticsSQLToolkitOptions,
  type QueryOutput,
  createAnalyticsSQLToolkit,
  formatQueryOutput
} from "./toolkit";

/** The `analytics_query` and `analytics_catalog` tools. */
export function analyticsSQLTools(
  options: AnalyticsSQLToolkitOptions
): ToolSet {
  const toolkit = createAnalyticsSQLToolkit(options);
  return {
    analytics_query: tool({
      description: toolkit.queryDescription,
      inputSchema: z.object({
        sql: z.string().describe("A single SQL statement.")
      }),
      execute: (input): Promise<QueryOutput> => toolkit.query(input),
      toModelOutput: ({ output }) => ({
        type: "text",
        value: formatQueryOutput(output)
      })
    }),
    analytics_catalog: tool({
      description: CATALOG_SEARCH_DESCRIPTION,
      inputSchema: z.object({
        query: z
          .string()
          .optional()
          .describe(
            'Words to match against table/column names and descriptions, e.g. "status code".'
          ),
        table: z
          .string()
          .optional()
          .describe(
            'A table name, e.g. "logs.workersLogs", for its full definition.'
          )
      }),
      execute: async (input) => toolkit.search(input)
    })
  };
}
