/**
 * AI SDK 7 adapter.
 *
 *   import { analyticsSQLTools } from "cf-agent-sql/ai-sdk";
 *   import { catalog } from "./analytics-catalog"; // generated by `asql render --out`
 *   const sql = analyticsSQLTools({ binding: env.ANALYTICS_SQL, catalog });
 *   new ToolLoopAgent({ model, instructions: sql.instructions, tools: sql.tools });
 */
import { tool, type ToolSet } from "ai";
import { z } from "zod";
import { CATALOG_SEARCH_DESCRIPTION } from "./catalog";
import {
  type AnalyticsSQLToolkitOptions,
  type QueryOutput,
  createAnalyticsSQLToolkit,
  formatQueryOutput
} from "./toolkit";

export interface AnalyticsSQLToolsOptions extends AnalyticsSQLToolkitOptions {
  /** Tool name prefix. Default "analytics". */
  prefix?: string;
}

export function analyticsSQLTools(options: AnalyticsSQLToolsOptions): {
  tools: ToolSet;
  instructions: string;
} {
  const toolkit = createAnalyticsSQLToolkit(options);
  const prefix = options.prefix ?? "analytics";

  const tools: ToolSet = {
    [`${prefix}_query`]: tool({
      description: toolkit.queryToolDescription(`${prefix}_catalog`),
      inputSchema: z.object({
        sql: z
          .string()
          .describe(
            "A single SELECT/WITH statement. Reference the time window as $start / $end."
          ),
        start: z
          .string()
          .optional()
          .describe(
            "Window start: ISO 8601 or relative (-15m, -1h, -7d). Default -1h."
          ),
        end: z
          .string()
          .optional()
          .describe("Window end: ISO 8601, relative, or 'now'. Default now."),
        params: z
          .record(
            z.string(),
            z.union([z.string(), z.number(), z.boolean(), z.null()])
          )
          .optional()
          .describe("Extra named params, referenced as $name.")
      }),
      execute: (input): Promise<QueryOutput> => toolkit.query(input),
      toModelOutput: ({ output }) => ({
        type: "text",
        value: formatQueryOutput(output)
      })
    })
  };

  tools[`${prefix}_catalog`] = tool({
    description: CATALOG_SEARCH_DESCRIPTION,
    inputSchema: z.object({
      query: z
        .string()
        .optional()
        .describe(
          'Words to match against table/column names and descriptions, e.g. "status code".'
        ),
      table: z
        .string()
        .optional()
        .describe(
          'A table name, e.g. "logs.workersLogs", for its full definition.'
        )
    }),
    execute: async (input) => toolkit.search(input)
  });

  return {
    tools,
    instructions: `You can query Cloudflare analytics with ${prefix}_query. Use ${prefix}_catalog to find tables and columns. Prefer aggregations over raw rows, always bound queries by time, and if a query fails read the error and retry with corrected SQL.`
  };
}
