/**
 * AI SDK 7 adapter.
 *
 *   import { analyticsSQLTools } from "cf-agent-sql/ai-sdk";
 *   import { catalog } from "./analytics-catalog"; // generated by `asql render --out`
 *   const sql = analyticsSQLTools({ binding: env.ANALYTICS_SQL, catalog });
 *   new ToolLoopAgent({ model, instructions: sql.instructions, tools: sql.tools });
 */
import { tool, type ToolSet } from "ai";
import { z } from "zod";
import {
  type AnalyticsSQLToolkitOptions,
  type QueryOutput,
  QUERY_TOOL_DESCRIPTION,
  createAnalyticsSQLToolkit,
  formatQueryOutput
} from "./toolkit";

export interface AnalyticsSQLToolsOptions extends AnalyticsSQLToolkitOptions {
  /**
   * Small catalogs are inlined into the query tool description. Larger ones get
   * a table list there plus a `<prefix>_describe` tool. Default budget 12k chars.
   */
  inlineBudgetChars?: number;
  /** Tool name prefix. Default "analytics". */
  prefix?: string;
}

export function analyticsSQLTools(options: AnalyticsSQLToolsOptions): {
  tools: ToolSet;
  instructions: string;
} {
  const toolkit = createAnalyticsSQLToolkit(options);
  const prefix = options.prefix ?? "analytics";
  const full = toolkit.renderCatalog("full");
  const inline = full.length <= (options.inlineBudgetChars ?? 12_000);

  const tools: ToolSet = {
    [`${prefix}_query`]: tool({
      description: `${QUERY_TOOL_DESCRIPTION}\n\n${inline ? `Schema:\n${full}` : `Tables (call ${prefix}_describe for columns first):\n${toolkit.renderCatalog("index")}`}`,
      inputSchema: z.object({
        sql: z
          .string()
          .describe(
            "A single SELECT/WITH statement. Reference the time window as $start / $end."
          ),
        start: z
          .string()
          .optional()
          .describe(
            "Window start: ISO 8601 or relative (-15m, -1h, -7d). Default -1h."
          ),
        end: z
          .string()
          .optional()
          .describe("Window end: ISO 8601, relative, or 'now'. Default now."),
        params: z
          .record(
            z.string(),
            z.union([z.string(), z.number(), z.boolean(), z.null()])
          )
          .optional()
          .describe("Extra named params, referenced as $name.")
      }),
      execute: (input): Promise<QueryOutput> => toolkit.query(input),
      toModelOutput: ({ output }) => ({
        type: "text",
        value: formatQueryOutput(output)
      })
    })
  };

  if (!inline) {
    tools[`${prefix}_describe`] = tool({
      description:
        "Columns, types, notes and example queries for analytics tables. Use instead of DESCRIBE / SHOW TABLES.",
      inputSchema: z.object({
        tables: z.array(z.string()).describe("Fully-qualified table names.")
      }),
      execute: async ({ tables }) => toolkit.describeTables(tables)
    });
  }

  return {
    tools,
    instructions: `You can query Cloudflare analytics with ${prefix}_query. Prefer aggregations over raw rows, always bound queries by time, and if a query fails read the HINT and retry with corrected SQL.`
  };
}
