/**
 * Pi Durable adapter.
 *
 *   import { analyticsSQLExtension } from "cf-agent-sql/pi";
 *   import { catalog } from "./analytics-catalog"; // generated by `asql render --out`
 *   registry.install(analyticsSQLExtension({ binding: env.ANALYTICS_SQL, catalog }));
 *
 * The query tool's description has the table index; columns come from the
 * catalog search tool. Both tools are replay-safe (read-only).
 */
import { Type } from "@earendil-works/pi-ai";
import {
  defineExtension,
  defineTool,
  type Extension
} from "@earendil-works/pi-durable";
import { CATALOG_SEARCH_DESCRIPTION } from "./catalog";
import {
  type AnalyticsSQLToolkitOptions,
  createAnalyticsSQLToolkit,
  formatQueryOutput
} from "./toolkit";

export interface AnalyticsSQLExtensionOptions extends AnalyticsSQLToolkitOptions {
  /** Extension name (what conversations select). Default "analytics-sql". */
  name?: string;
  /** Tool name prefix. Default "analytics". */
  prefix?: string;
}

export function analyticsSQLExtension(
  options: AnalyticsSQLExtensionOptions
): Extension {
  const toolkit = createAnalyticsSQLToolkit(options);
  const prefix = options.prefix ?? "analytics";

  const query = defineTool({
    name: `${prefix}_query`,
    description: toolkit.queryToolDescription(`${prefix}_catalog`),
    parameters: Type.Object({
      sql: Type.String({
        description:
          "A single SELECT/WITH statement. Reference the time window as $start / $end."
      }),
      start: Type.Optional(
        Type.String({
          description:
            "Window start: ISO 8601 or relative (-15m, -1h, -7d). Default -1h."
        })
      ),
      end: Type.Optional(
        Type.String({
          description: "Window end: ISO 8601, relative, or 'now'. Default now."
        })
      ),
      params: Type.Optional(
        Type.Record(
          Type.String(),
          Type.Union([
            Type.String(),
            Type.Number(),
            Type.Boolean(),
            Type.Null()
          ]),
          {
            description: "Extra named params, referenced as $name."
          }
        )
      )
    }),
    replay: "safe",
    outputLimits: { maxBytes: 64_000, retain: "head" },
    execute: async (args) => {
      const out = await toolkit.query(args);
      return {
        content: [{ type: "text", text: formatQueryOutput(out) }],
        isError: !out.ok,
        details: out.ok
          ? {
              rowCount: out.rowCount,
              truncated: out.truncated,
              window: out.window
            }
          : null
      };
    }
  });

  const catalog = defineTool({
    name: `${prefix}_catalog`,
    description: CATALOG_SEARCH_DESCRIPTION,
    parameters: Type.Object({
      query: Type.Optional(
        Type.String({
          description:
            'Words to match against table/column names and descriptions, e.g. "status code".'
        })
      ),
      table: Type.Optional(
        Type.String({
          description:
            'A table name, e.g. "logs.workersLogs", for its full definition.'
        })
      )
    }),
    replay: "safe",
    execute: async (args) => ({
      content: [{ type: "text", text: toolkit.search(args) }],
      details: null
    })
  });

  return defineExtension({
    name: options.name ?? "analytics-sql",
    tools: [query, catalog]
  });
}
