/**
 * Pi Durable adapter.
 *
 *   import { analyticsSQLExtension } from "cf-agent-sql/pi";
 *   import { catalog } from "./analytics-catalog"; // generated by `asql render --out`
 *   registry.install(analyticsSQLExtension({ binding: env.ANALYTICS_SQL, catalog }));
 *
 * The schema goes in a system prompt section (pi diffs sections, so the prompt
 * cache survives) and the query tool is marked replay-safe (read-only).
 */
import { Type } from "@earendil-works/pi-ai";
import {
  defineExtension,
  defineTool,
  section,
  type Extension
} from "@earendil-works/pi-durable";
import {
  type AnalyticsSQLToolkitOptions,
  QUERY_TOOL_DESCRIPTION,
  createAnalyticsSQLToolkit,
  formatQueryOutput
} from "./toolkit";

export interface AnalyticsSQLExtensionOptions extends AnalyticsSQLToolkitOptions {
  /** Extension name (what conversations select). Default "analytics-sql". */
  name?: string;
  /** Tool name prefix. Default "analytics". */
  prefix?: string;
}

export function analyticsSQLExtension(
  options: AnalyticsSQLExtensionOptions
): Extension {
  const toolkit = createAnalyticsSQLToolkit(options);
  const prefix = options.prefix ?? "analytics";
  const schema = toolkit.renderCatalog("full");

  const query = defineTool({
    name: `${prefix}_query`,
    description: `${QUERY_TOOL_DESCRIPTION}\nThe schema is in the <analytics_schema> section of the system prompt.`,
    parameters: Type.Object({
      sql: Type.String({
        description:
          "A single SELECT/WITH statement. Reference the time window as $start / $end."
      }),
      start: Type.Optional(
        Type.String({
          description:
            "Window start: ISO 8601 or relative (-15m, -1h, -7d). Default -1h."
        })
      ),
      end: Type.Optional(
        Type.String({
          description: "Window end: ISO 8601, relative, or 'now'. Default now."
        })
      ),
      params: Type.Optional(
        Type.Record(
          Type.String(),
          Type.Union([
            Type.String(),
            Type.Number(),
            Type.Boolean(),
            Type.Null()
          ]),
          {
            description: "Extra named params, referenced as $name."
          }
        )
      )
    }),
    replay: "safe",
    outputLimits: { maxBytes: 64_000, retain: "head" },
    execute: async (args) => {
      const out = await toolkit.query(args);
      return {
        content: [{ type: "text", text: formatQueryOutput(out) }],
        isError: !out.ok,
        details:
          out.ok && out.kind === "rows"
            ? {
                rowCount: out.rowCount,
                truncated: out.truncated,
                window: out.window
              }
            : null
      };
    }
  });

  return defineExtension({
    name: options.name ?? "analytics-sql",
    tools: [query],
    sections: [section("analytics_schema", () => schema)]
  });
}
