/**
 * Pi Durable adapter.
 *
 *   import { analyticsSQLExtension } from "cf-agent-sql/pi";
 *   import { catalog } from "./analytics-catalog"; // generated by `asql render --out`
 *   registry.install(analyticsSQLExtension({ binding: env.ANALYTICS, catalog }));
 *
 * Adds the `analytics_query` and `analytics_catalog` tools. Both are read-only,
 * so they're marked safe to replay.
 */
import { Type } from "@earendil-works/pi-ai";
import {
  defineExtension,
  defineTool,
  type Extension
} from "@earendil-works/pi-durable";
import { CATALOG_SEARCH_DESCRIPTION } from "./catalog";
import {
  type AnalyticsSQLToolkitOptions,
  createAnalyticsSQLToolkit,
  formatQueryOutput
} from "./toolkit";

export function analyticsSQLExtension(
  options: AnalyticsSQLToolkitOptions
): Extension {
  const toolkit = createAnalyticsSQLToolkit(options);

  const query = defineTool({
    name: "analytics_query",
    description: toolkit.queryDescription,
    parameters: Type.Object({
      sql: Type.String({ description: "A single SQL statement." })
    }),
    replay: "safe",
    execute: async (args) => {
      const out = await toolkit.query(args);
      return {
        content: [{ type: "text", text: formatQueryOutput(out) }],
        isError: !out.ok,
        details: null
      };
    }
  });

  const catalog = defineTool({
    name: "analytics_catalog",
    description: CATALOG_SEARCH_DESCRIPTION,
    parameters: Type.Object({
      query: Type.Optional(
        Type.String({
          description:
            'Words to match against table/column names and descriptions, e.g. "status code".'
        })
      ),
      table: Type.Optional(
        Type.String({
          description:
            'A table name, e.g. "logs.workersLogs", for its full definition.'
        })
      )
    }),
    replay: "safe",
    execute: async (args) => ({
      content: [{ type: "text", text: toolkit.search(args) }],
      details: null
    })
  });

  return defineExtension({ name: "analytics-sql", tools: [query, catalog] });
}
